# -*- coding: utf-8 -*-
"""non-diagonal-cov.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-_re-k4AJtpgWTIpVKng_pOkdy7rNDSz
"""

# !unzip PySESM.zip
# !pip install torchmetrics
# !mkdir results_1
# !mkdir results_2
# !mkdir results_3
# !mkdir results_1/plots
# !mkdir results_2/plots
# !mkdir results_3/plots
# !mkdir results_1/stats
# !mkdir results_2/stats
# !mkdir results_3/stats

import torch
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from mpl_toolkits.mplot3d import Axes3D
from scipy.stats import multivariate_normal
from torchmetrics import MeanSquaredError, Accuracy, Precision, Recall, F1Score
from sklearn.model_selection import RandomizedSearchCV

from PySESM.models.SESM.SESM import SESM_Model
from PySESM.base_functions.Function import GaussianFunctions
from google.colab import files
import plotly.express as px

"""## Definicion de covarianzas no diagnonales"""

# Non-diagonal covariance
def generate_sigma_tensors():
    """
    Generates non-diagonal covariance tensors for 2D Gaussian distributions.

    Returns:
    tuple: Tuple containing three non-diagonal covariance tensors (sigma1, sigma2, sigma3).
    """
    e0 = torch.tensor([1.0, 1.0], dtype=torch.float32)
    e0 = e0 / e0.norm()

    def generate_sigma(rotation_angle, scaling_factors):
        rotation_matrix = torch.tensor([[np.cos(rotation_angle), -np.sin(rotation_angle)],
                                       [np.sin(rotation_angle), np.cos(rotation_angle)]], dtype=torch.float32)
        e = torch.mm(rotation_matrix, e0.unsqueeze(1))
        E = torch.cat((e0.unsqueeze(1), e), dim=1)
        D = torch.diag(torch.tensor(scaling_factors, dtype=torch.float32))
        return torch.mm(torch.mm(E, D), E.t())

    sigma1 = generate_sigma(np.pi/4, [0.4, 0.1])
    sigma2 = generate_sigma(np.pi/4, [0.05, 0.5])
    sigma3 = generate_sigma(np.pi/4, [0.2, 0.5])

    return sigma1, sigma2, sigma3

sigma1, sigma2, sigma3 = generate_sigma_tensors()

"""## Definicion de varianzas diagonales"""

sigma1_d = 0.15 * torch.eye(2)
sigma2_d = 0.2 * torch.eye(2)
sigma3_d = 0.3 *torch.eye(2)

"""## Crear Gaussianas"""

def generate_mesh_and_z(sigma1, sigma2, sigma3):
    """
    Generates a mesh grid and corresponding probability density values for a mixture
    of three 2D Gaussian distributions.

    Args:
    sigma1 (torch.Tensor): The covariance tensor for the first Gaussian distribution.
    sigma2 (torch.Tensor): The covariance tensor for the second Gaussian distribution.
    sigma3 (torch.Tensor): The covariance tensor for the third Gaussian distribution.

    Returns:
    tuple: Tuple containing mesh grid arrays (xx, yy) and the corresponding probability
    density values (zz).
    """
    N_points = 50
    xl = -2
    xr = 2

    x = np.linspace(xl, xr, N_points+1)
    xx, yy = np.meshgrid(x, x)

    X = torch.tensor(np.column_stack([xx.ravel(), yy.ravel()]), dtype=torch.float32)

    mu1 = torch.tensor([1, 1], dtype=torch.float32)
    mu2 = torch.tensor([1, -1], dtype=torch.float32)
    mu3 = torch.tensor([-1, -1], dtype=torch.float32)

    z1 = torch.tensor(multivariate_normal.pdf(X.numpy(), mu1.numpy(), sigma1.numpy()), dtype=torch.float32)
    z2 = torch.tensor(multivariate_normal.pdf(X.numpy(), mu2.numpy(), sigma2.numpy()), dtype=torch.float32)
    z3 = torch.tensor(multivariate_normal.pdf(X.numpy(), mu3.numpy(), sigma3.numpy()), dtype=torch.float32)

    zz = (z1 + z2 + z3).reshape(xx.shape)

    return xx, yy, zz

"""## Covarianza de gaussianas del experimento
  - 3 Diagonales
  - 2 Diagonales, 1 no diagonal
  - 1 diagonal, 2 no diagonales
  - 3 no diagonales
"""

# 3 diag
xx, yy, zz = generate_mesh_and_z(sigma1_d, sigma2_d, sigma3_d)

# 2 diag, 1 no diag
xx_1, yy_1, zz_1 = generate_mesh_and_z(sigma1_d, sigma2_d, sigma3)

# 1 diag, 2 no diag
xx_2, yy_2, zz_2 = generate_mesh_and_z(sigma1_d, sigma2, sigma3)
# 3 no diag
xx_3, yy_3, zz_3 = generate_mesh_and_z(sigma1, sigma2, sigma3)

fig = go.Figure(data=[go.Surface(z=zz_3.numpy(), x=xx_3, y=yy_3)])
fig.update_layout(scene=dict(aspectmode='data'))
fig.update_layout(scene=dict(camera=dict(eye=dict(x=2, y=2, z=1))))

#fig.show()

"""# Configuracion y y ejecucion del modelo"""

import pandas as pd

def generate_uniform_sampling(total_points, n_samples=500, min_separation=1):
    """
    Generate uniform sampling indices with a minimum separation criterion.

    Args:
        total_points (int): Total number of data points.
        n_samples (int): Number of samples to generate (default is 500).
        min_separation (int): Minimum separation between selected indices (default is 1).

    Returns:
        list: List of selected indices.

    Example:
        sampled_indices = generate_uniform_sampling(1000, n_samples=200, min_separation=2)
    """

    selected_indexes = []
    while len(selected_indexes) < n_samples:
        random_index = np.random.randint(total_points)
        if all(abs(random_index - existing_index) >= min_separation for existing_index in selected_indexes):
            selected_indexes.append(random_index)
    return selected_indexes

def sample_data(x_values, y_values, z_values, sampled_indices):
    """
    Sample data based on selected indices.

    Args:
        x_values (array-like): X-axis values.
        y_values (array-like): Y-axis values.
        z_values (array-like): Z-axis values.
        sampled_indices (list): List of indices to sample.

    Returns:
        tuple: Tuple containing sampled X (features) and y (labels).

    Example:
        X, y = sample_data(x_values, y_values, z_values, sampled_indices)
    """

    sampled_x = torch.tensor(x_values[sampled_indices], dtype=torch.float32)
    sampled_y = torch.tensor(y_values[sampled_indices], dtype=torch.float32)
    X = torch.stack((sampled_x, sampled_y), dim=1)
    y = z_values[sampled_indices].clone().detach().to(dtype=torch.float32)
    return X, y

def build_model(n_samples, n_features, l_functions):
    """
    Build and configure the SESM (Sparse Evolutionary Structural Modeling) model.

    Args:
    - n_samples (int): Number of training samples.
    - n_features (int): Number of features.
    - l_functions (int): Number of Gaussian functions.

    Returns:
    SESM_Model: An instance of the SESM model.
    """
    gaussian_function = GaussianFunctions(n_features=n_features, n_functions=l_functions)
    model = SESM_Model(
        n_samples=n_samples,
        n_features=n_features,
        n_functions=l_functions,
        psi=gaussian_function.gaussian
    )
    return model

def train_model(model, X, y, model_epochs, ista_epochs, ista_alpha, ista_lambd, dictionary_epochs, dictionary_alpha):
    """
    Train the SESM model using the specified training parameters.

    Args:
    - model (SESM_Model): The SESM model to be trained.
    - X (torch.Tensor): Input features.
    - y (torch.Tensor): Target values.
    - model_epochs (int): Number of epochs for training the overall model.
    - ista_epochs (int): Number of ISTA (Iterative Shrinkage-Thresholding Algorithm) epochs.
    - ista_alpha (float): ISTA alpha parameter.
    - ista_lambd (float): ISTA lambda parameter.
    - dictionary_epochs (int): Number of epochs for updating the dictionary.
    - dictionary_alpha (float): Dictionary update alpha parameter.

    Returns:
    None
    """

    model.fit(
        X=X,
        y=y,
        model_epochs=model_epochs,
        ista_epochs=ista_epochs,
        ista_alpha=ista_alpha,
        ista_lambd=ista_lambd,
        dictionary_epochs=dictionary_epochs,
        dictionary_alpha=dictionary_alpha
    )

def plot_scatter(x_values, y_values, z_values, Z, hypset, fngroup, iteration):
    """
    Plot a scatter plot for the original function and the surrogate model.

    Args:
        x_values (array-like): X-axis values.
        y_values (array-like): Y-axis values.
        z_values (array-like): Z-axis values for the original function.
        Z (array-like): Z-axis values for the surrogate model.
        hypset (int): Hypothesis set or configuration identifier.
        fngroup (int): Function group identifier.
        iteration (int): Iteration number.

    Returns:
        None: Saves the plot as an image file.

    Example:
        plot_scatter(x_values, y_values, z_values, Z, 3, 1 , 1)
    """
    fig = plt.figure(figsize=(13, 13))

    ax1 = fig.add_subplot(221, projection='3d')
    ax1.scatter(x_values, y_values, z_values, c=z_values)
    ax1.set_xlabel('X')
    ax1.set_ylabel('Y')
    ax1.set_zlabel('Z')
    ax1.set_title('Original Function')

    ax2 = fig.add_subplot(222, projection='3d')
    ax2.scatter(x_values, y_values, Z.clone().detach(), c=Z.clone().detach())
    ax2.set_xlabel('X')
    ax2.set_ylabel('Y')
    ax2.set_zlabel('Z')
    ax2.set_title('Surrogate Model')
    ax2.set_zlim(0)

    filename = f"results_{hypset}/plots/{fngroup}.{iteration}.png"
    plt.savefig(filename)

    plt.clf()

def evaluate_model(model, x_values, y_values, z_values, hypset, fngroup, iter, debug=True):
    """
    Evaluate the SESM model's performance on a dataset.

    Args:
    - model (SESM_Model): The trained SESM model.
    - x_values (Union[np.ndarray, list]): Input feature values along the x-axis.
    - y_values (Union[np.ndarray, list]): Input feature values along the y-axis.
    - z_values (Union[np.ndarray, list]): Target values.
    - hypset (str): Hypothesis set identifier.
    - fngroup (str): Function group identifier (Dataset).
    - iter (int): Iteration number.
    - debug (bool): Whether to generate and save debugging plots (default is True).

    Returns:
    Tuple[float, float]: Tuple containing time taken for evaluation (in minutes) and
    the Mean Squared Error (MSE) value.
    """
    #----------------PREDICTION------------
    x_tensor = torch.tensor(x_values)
    y_tensor = torch.tensor(y_values)
    XY = torch.cat((x_tensor.unsqueeze(1), y_tensor.unsqueeze(1)), dim=1)
    Z = model.predict(XY)

    #----------------- ANALYSIS------------
    time = model.time / 60
    mse = MeanSquaredError()
    mse(Z.clone().detach(), z_values)
    mse_value = mse.compute()

    if debug:
        plot_scatter(x_values, y_values, z_values, Z, hypset, fngroup, iter)

        df = pd.DataFrame({
            'Loss': model.losses
        })

        df.to_csv(f'results_{hypset}/stats/{iter}.csv', index=False)

    return time, mse_value

def run_experiment(_x, _y, _z, hyperparams, fngroup, iter, debug=True):
    """
    Run a complete SESM experiment, including data sampling, model training, and evaluation.

    Args:
    - _x (np.ndarray): Input feature values along the x-axis.
    - _y (np.ndarray): Input feature values along the y-axis.
    - _z (np.ndarray): Target values.
    - hyperparams (dict): Hyperparameters for the experiment.
    - fngroup (str): Function group identifier.
    - iter (int): Iteration number.
    - debug (bool): Whether to generate and save debugging plots (default is True).

    Returns:
    Tuple[float, float]: Tuple containing time taken for the experiment (in minutes)
    and the Mean Squared Error (MSE) value.
    """
    x_values = _x.ravel()
    y_values = _y.ravel()
    z_values = _z.ravel()

    total_points = len(x_values)

    sampled_indices = generate_uniform_sampling(total_points)
    X, y = sample_data(x_values, y_values, z_values, sampled_indices)

    model = build_model(n_samples=hyperparams["n_samples"], n_features=hyperparams["n_features"], l_functions=hyperparams["l_functions"])

    model_epochs = hyperparams["m_epochs"]
    ista_epochs = hyperparams["h_epochs"]
    dictionary_epochs = hyperparams["dict_epochs"]

    ista_alpha = hyperparams["ista_alpha"]
    ista_lambd = hyperparams["ista_lambd"]
    dictionary_alpha = hyperparams["dictionary_alpha"]

    train_model(model, X, y, model_epochs, ista_epochs, ista_alpha, ista_lambd, dictionary_epochs, dictionary_alpha)
    time, mse_value = evaluate_model(model, x_values, y_values, z_values, hyperparams["hyp_set"],  fngroup, iter, debug)
    return time, mse_value

def plot_stats(directory, num_files):
    """
    Plot statistics for loss values from multiple CSV files.

    Args:
        directory (str): The directory containing CSV files.
        num_files (int): The number of CSV files to process.

    Returns:
        None: Displays an interactive plot and saves an HTML file.

    Note:
        Assumes that each CSV file contains loss values for the same number of epochs.

    """
    fig = px.scatter(title='Loss analysis')
    m_epochs_losses = []

    for i in range(num_files):
        file_path = f"{directory}/stats/{i}.csv"

        df = pd.read_csv(file_path)
        m_epochs_losses.append(df)

    merged_losses = pd.concat(m_epochs_losses, axis=1)

    # Compute mean, std, min, and max for each row
    summary_df = pd.DataFrame({
        'Mean': merged_losses.mean(axis=1),
        'Std': merged_losses.std(axis=1),
        'Min': merged_losses.min(axis=1),
        'Max': merged_losses.max(axis=1)
    })

    summary_df.to_csv(f'{directory}/stats/processed.csv', index=False)

    fig.add_scatter(
        x=summary_df.index,
        y=summary_df['Mean'],
        mode='lines+markers',
        error_y=dict(type='data', array=summary_df['Std']),
        name='Mean'
    )

    fig.add_scatter(
        x=summary_df.index,
        y=summary_df['Max'],
        mode='markers',
        name='Max'
    )

    fig.add_scatter(
        x=summary_df.index,
        y=summary_df['Min'],
        mode='markers',
        name='Min'
    )

    fig.update_layout(
        xaxis_title='m_epochs',
        yaxis_title='Loss',
        legend_title='Legend',
        showlegend=True
    )
    fig.show()
    fig.write_html(f"interactive_plot-{directory}.html")

import csv

def save_results(data, fngroup):
  # Compute Mean and Std for executio
  times = [item[1] for item in data]
  mse_values = [item[2] for item in data]

  average_time = np.mean(times)
  std_time = np.std(times)
  average_mse = np.mean(mse_values)
  std_mse = np.std(mse_values)

  with open(f"results_{fngroup}.csv", mode="w", newline="") as file:
      writer = csv.writer(file)
      writer.writerow(["Repetion", "Time (min)", "MSE"])
      writer.writerows(data)
      writer.writerow(["Mean", average_time, average_mse])
      writer.writerow(["Std", std_time, std_mse])

"""# Nomenclatura de experimentos

<Set de hiperparámetros>. <Set de datos (conjunto de gaussianas)>.<Número de repetición del experimento>

## Set de Hiperparámetros
|  Hiperparámetro | Exp 1.x.x     | Exp 2.x.x     | Exp 3.x.x     |
|-----------------|---------------|---------------|---------------|
| n_samples       | 50            | 100           | 500           |
| n_features      | 2             | 2             | 2             |
| l_functions     | 20            | 6             | 10            |
| ista_alpha      | 0.06          | 0.0125        | 0.0125        |
| ista_lambd      | 0.005         | 0.001         | 0.001         |
| dictionary_alpha| 0.06          | 0.0125        | 0.0125        |
| m_epochs        | 25            | 500           | 300           |
| dict_epochs     | 800           | 20            | 60            |
| h_epochs        | 1000          | 50            | 100           |

### Set de datos

|     Set      | Exp 1.x.x     | Exp 2.x.x     | Exp 3.x.x     |
|-----------------|---------------|---------------|---------------|
| Gaussianas 1    | Exp 1.1.x     | Exp 2.1.x     | Exp 3.1.x     |
| Gaussianas 2    | Exp 1.2.x     | Exp 2.2.x     | Exp 3.2.x     |
| Gaussianas 3    | Exp 1.3.x     | Exp 2.3.x     | Exp 3.3.x     |
| Gaussianas 4    | Exp 1.4.x     | Exp 2.4.x     | Exp 3.4.x     |
"""

N_iter = 5 #
experiment_3 = {
      "hyp_set": 3,
      "n_samples"	: 500,
      "n_features" : 2,
      "l_functions":  10,
      "ista_alpha"	: 0.0125,
      "ista_lambd"	 : 0.001,
      "dictionary_alpha": 0.0125,
      "m_epochs" : 20,
      "dict_epochs": 60,
      "h_epochs": 100
}
#1, 2, 3 --> m_epochs

data = []
for i in range(N_iter):
  time, mse = run_experiment(xx,yy,zz,
                            experiment_3, fngroup=1, iter=i)
  data.append((i, time, mse.item()))

save_results(data=data, fngroup=1)

stats_dir = f'results_{experiment_3["hyp_set"]}'
plot_stats(stats_dir, N_iter)

"""# Correr experimentos"""

data_1 = []

for i in range(N_iter):
  time, mse = run_experiment(xx_1,yy_1,zz_1,
                            experiment_3, fngroup=2, iter=i)
  data_1.append((i, time, mse.item()))

save_results(data=data_1, fngroup=2)

data_2 = []
for i in range(N_iter):
  time, mse = run_experiment(xx_2,yy_2,zz_2,
                            experiment_3,fngroup=3, iter=i)
  data_2.append((i, time, mse.item()))

save_results(data=data_2, fngroup=3)

data_3 = []
for i in range(N_iter):
  time, mse = run_experiment(xx_3,yy_3,zz_3,
                            experiment_3, fngroup=4, iter=i)
  data_3.append((i, time, mse.item()))

save_results(data=data_3, fngroup=4)

files.download('results_1.csv')
!zip -r results_1.zip results_1/
files.download('results_1.zip')

files.download('results_2.csv')
!zip -r results_2.zip results_2/
files.download('results_2.zip')

files.download('results_3.csv')
!zip -r results_3.zip results_3/
files.download('results_3.zip')